<?php

// DO NOT EDIT THIS FILE

// this will autoload the class that we need in our code
spl_autoload_register(function($class) {
 
    // we are assuming that it is in the same directory as this file
    // otherwise we have to do
    // $path = 'path/to/' . $class . ".php"    
    $path =  $class . ".php";
    require $path; 
  
});
 