<?php 

// DO NOT EDIT THIS FILE

class Line {
    public $startRow;
    public $startCol;
    public $endRow;
    public $endCol;

    function __construct( $startRow, $startCol, $endRow, $endCol) {
        $this->startRow = $startRow;
        $this->startCol = $startCol;
        $this->endRow = $endRow;
        $this->endCol = $endCol;
    }

    function __toString() {
        return "($this->startRow,$this->startCol)-($this->endRow,$this->endCol)";
    }
}