<?php

// DO NOT EDIT THIS FILE

require_once "common.php";
require_once "q4.php";

// Test functions
function printBoard($board) {
    echo "<table border='1'>\n";
    foreach ($board as $row) {
        echo "<tr>\n";
        foreach ($row as $cell) {
            echo "<td>$cell</td>\n";
        }
        echo "</tr>\n";
    }    
    echo "</table>\n";
}

function testMatch($sequence, $board, $expected) {
    $match = match($sequence, $board);
    if ( $match === false && $expected === false) {
        $match = "false";
        $expected = "false";
        $result = "Pass";
    }
    elseif ( strcmp( "$match", $expected) === 0 )  {
            $result = "Pass";
    }
    else {
        $result = "Fail";
    }

    echo "Sequence: [" . implode(",", $sequence) ."]</br>\n";
    echo "Expected: $expected<br/>\n";
    echo "Actual: $match<br/>\n";
    echo "Result: <b>$result</b><br/>\n";
    echo "<br/>\n";
}
?>

<html>
<body>
    <b>Board</b>
    <?php
        $board = [
            [ 3,  7, 11, 12],
            [ 8, 15,  1, 10],
            [14,  2 , 4,  5],
            [ 9, 13, 16,  6],
        ];
        printBoard($board);
        echo "<br/>\n";

        echo "<b>Row</b><br/>\n";
        testMatch( [10, 1, 15, 8], $board, "(1,0)-(1,3)");
        testMatch( [14, 2, 5], $board, false);

        echo "<b>Column</b><br/>\n";
        testMatch( [13, 2, 15], $board, "(1,1)-(3,1)");
        testMatch( [13, 2, 7], $board, false);

        echo "<b>Diagonal</b><br/>\n";
        testMatch( [4, 3, 15], $board, "(0,0)-(2,2)");
        testMatch( [9, 1, 12, 2], $board, "(0,3)-(3,0)");
        testMatch( [9, 1, 12], $board, false);

        echo "<b>Others</b><br/>\n";
        testMatch( [4], $board, "(2,2)-(2,2)");
        testMatch( [13, 16, 6, 7], $board, false);
        testMatch( [9, 4, 1, 12], $board, false);
        testMatch( [1, 2, 3, 4, 5], $board, false);
    ?>
</body>
</html>
